### ISSUE TITLE
running into syntax errors, when running a list of commands

### ISSUE THREAD

**Issue by kobyys** [deangelo-llooker/gzr#13]
Hello,

Recently I installed gazer on a debian8 VM. In general it is working fine. However there is a bunch of commands which produce syntax errors. I am curious, where this comes from and if it's specific problem with our setup or if something changed with looker version `5.24`potentially. Maybe someone can replicate this.

I get the syntax error for these commands, it is always about an unexpected '.' 
```
gzr plan ls
gzr user ls
gzr connection ls
```

This is what the error looks like:

```
gzr plan ls --host=my.looker.tls
/var/lib/gems/2.1.0/gems/gazer-0.2.6/lib/gzr/commands/plan/ls.rb:61:in `eval': (eval):1: syntax error, unexpected '.' (SyntaxError)
row.user&.id
          ^
        from /var/lib/gems/2.1.0/gems/gazer-0.2.6/lib/gzr/commands/plan/ls.rb:61:in `block (3 levels) in execute'
        from /var/lib/gems/2.1.0/gems/gazer-0.2.6/lib/gzr/commands/plan/ls.rb:60:in `collect'
        from /var/lib/gems/2.1.0/gems/gazer-0.2.6/lib/gzr/commands/plan/ls.rb:60:in `block (2 levels) in execute'
        from /var/lib/gems/2.1.0/gems/gazer-0.2.6/lib/gzr/commands/plan/ls.rb:59:in `map'
        from /var/lib/gems/2.1.0/gems/gazer-0.2.6/lib/gzr/commands/plan/ls.rb:59:in `block in execute'
        from /var/lib/gems/2.1.0/gems/gazer-0.2.6/lib/gzr/modules/session.rb:163:in `with_session'
        from /var/lib/gems/2.1.0/gems/gazer-0.2.6/lib/gzr/commands/plan/ls.rb:19:in `execute'
        from /var/lib/gems/2.1.0/gems/gazer-0.2.6/lib/gzr/commands/plan.rb:123:in `ls'
        from /var/lib/gems/2.1.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.1.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.1.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.1.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
        from /var/lib/gems/2.1.0/gems/thor-0.20.0/lib/thor.rb:238:in `block in subcommand'
        from /var/lib/gems/2.1.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.1.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.1.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.1.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /var/lib/gems/2.1.0/gems/gazer-0.2.6/exe/gzr:14:in `<top (required)>'
        from /usr/local/bin/gzr:23:in `load'
        from /usr/local/bin/gzr:23:in `<main>
```
All the other commands I've been testing, have been working fine.
Could somebody potentially give me any insight on why this is happening?
Thanks!

**Comment by deangelo-llooker** [comment]
What version of Ruby are you using. The `&.` operator is introduced in Ruby 2.3.

**Comment by kobyys** [comment]
That actually was the problem! I was running Ruby 2.1.
After upgrading to 2.5 and reinstalling the gem, it works like a charm.
Thank you very much!

**Comment by deangelo-llooker** [comment]
I added a line to the file gzr.gemspec so that the requirement for Ruby 2.3 is enforced.
