### ISSUE TITLE
Network timeout when dashboard import

### ISSUE THREAD

**Issue by AlexeyV-Turner** [deangelo-llooker/gzr#17]
the error message below:

**Comment by AlexeyV-Turner** [comment]
options: {"debug"=>true, "host"=>"tiprod.looker._______.com", "port"=>"19999", "ssl"=>true, "verify_ssl"=>true, "force"=>true, "client_id"=>"**********", "client_secret"=>"**********"}
API 3.1 available? true
connecting to {:api_endpoint=>"https://tiprod.looker._______.com:19999/api/3.1", :connection_options=>{:ssl=>{:verify=>true, :verify_mode=>3}}, :user_agent=>"Gazer 0.2.6", :client_id=>"**********", :client_secret=>"**********"}
check for connectivity: true
verify authentication: true
logout
/usr/share/ruby/2.3.0/net/protocol.rb:176:in `rbuf_fill': Net::ReadTimeout (Faraday::TimeoutError)
        from /usr/share/ruby/2.3.0/net/protocol.rb:154:in `readuntil'
        from /usr/share/ruby/2.3.0/net/protocol.rb:164:in `readline'
        from /usr/share/ruby/2.3.0/net/http/response.rb:40:in `read_status_line'
        from /usr/share/ruby/2.3.0/net/http/response.rb:29:in `read_new'
        from /usr/share/ruby/2.3.0/net/http.rb:1423:in `block in transport_request'
        from /usr/share/ruby/2.3.0/net/http.rb:1420:in `catch'
        from /usr/share/ruby/2.3.0/net/http.rb:1420:in `transport_request'
        from /usr/share/ruby/2.3.0/net/http.rb:1393:in `request'
        from /usr/share/ruby/2.3.0/net/http.rb:1386:in `block in request'
        from /usr/share/ruby/2.3.0/net/http.rb:853:in `start'
        from /usr/share/ruby/2.3.0/net/http.rb:1384:in `request'
        from /usr/share/ruby/2.3.0/net/http.rb:1142:in `get'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:85:in `perform_request'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:43:in `block in call'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/faraday-0.15.3/lib/faraday/adapter/net_http.rb:38:in `call'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/faraday-0.15.3/lib/faraday/response.rb:8:in `call'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/faraday-0.15.3/lib/faraday/rack_builder.rb:143:in `build_response'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/faraday-0.15.3/lib/faraday/connection.rb:387:in `run_request'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/faraday-0.15.3/lib/faraday/connection.rb:138:in `get'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/sawyer-0.8.1/lib/sawyer/agent.rb:94:in `call'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client.rb:280:in `request'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client.rb:72:in `get'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client/dynamic.rb:96:in `invoke_remote'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/looker-sdk-0.0.6/lib/looker-sdk/client/dynamic.rb:63:in `method_missing'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/gazer-0.2.6/lib/gzr/modules/dashboard.rb:34:in `search_dashboards_by_slug'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard/import.rb:60:in `sync_dashboard'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard/import.rb:35:in `block (2 levels) in execute'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/gazer-0.2.6/lib/gzr/modules/filehelper.rb:57:in `read_file'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard/import.rb:33:in `block in execute'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/gazer-0.2.6/lib/gzr/modules/session.rb:163:in `with_session'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard/import.rb:29:in `execute'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/gazer-0.2.6/lib/gzr/commands/dashboard.rb:37:in `import'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:115:in `invoke'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor.rb:238:in `block in subcommand'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
        from /home/avitkalov/.gem/ruby/2.3.0/gems/gazer-0.2.6/exe/gzr:14:in `<top (required)>'
        from /home/avitkalov/bin/gzr:23:in `load'
        from /home/avitkalov/bin/gzr:23:in `<main>'

**Comment by AlexeyV-Turner** [comment]
However when I do "gzr dashboard cat" for some another dashboard it works fine with the same credentials and the same server
