### ISSUE TITLE
Support for space export for files with a containing “/” in content's name

### ISSUE THREAD

**Issue by davidtamaki** [deangelo-llooker/gzr#5]
Currently the `space export` function breaks for content that have a "/" in the name. Running `gzr space export N --debug  --dir .` returns the following error message:

```
/Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/modules/filehelper.rb:34:in `initialize': No such file or directory @ rb_sysopen - /Users/David/.../Look_N_abc/xyz.json (Errno::ENOENT)
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/modules/filehelper.rb:34:in `open'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/modules/filehelper.rb:34:in `write_file'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:67:in `block in process_space'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:65:in `each'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:65:in `process_space'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:79:in `block in process_space'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:78:in `each'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:78:in `process_space'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:79:in `block in process_space'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:78:in `each'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:78:in `process_space'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:50:in `block in execute'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/modules/session.rb:138:in `with_session'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space/export.rb:27:in `execute'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/lib/gzr/commands/space.rb:55:in `export'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:115:in `invoke'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor.rb:238:in `block in subcommand'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
    from /Users/David/.rvm/gems/ruby-2.3.0/gems/gazer-0.1.8/exe/gzr:14:in `top (required)'
    from /Users/David/.rvm/gems/ruby-2.3.0/bin/gzr:23:in `load'
    from /Users/David/.rvm/gems/ruby-2.3.0/bin/gzr:23:in `main'
    from /Users/David/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
    from /Users/David/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `main'
```

**Comment by carldickson** [comment]
Also | characters 

Great tool but until these are fixed I cant use it :(
